# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=16)),
                ('nombre_factura', models.CharField(choices=[('Agua', 'Agua'), ('Luz', 'Luz'), ('Telefono', 'Telefono')], default='Agua', max_length=8)),
                ('fecha_maxima', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_factura', models.CharField(choices=[('Pagado', 'Pagado'), ('Pendiente', 'Pendiente'), ('Acumulado', 'Acumulado')], default='Pagado', max_length=11)),
            ],
        ),
    ]
