# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=16)),
                ('echa_pago', models.DateField()),
                ('nombre_de_quien_recibe', models.CharField(max_length=30)),
                ('concepto_recibo', models.CharField(choices=[('Agua', 'Agua'), ('Luz', 'Luz'), ('Telefono', 'Telefono')], default='Agua', max_length=8)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
