# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_recibo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='echa_pago',
            new_name='fecha_pago',
        ),
    ]
